---
deployment:
  tasks:
    - export DEPLOYPATH=$HOME/public_html/wp-content/uploads/greektax
    - /bin/cp -r src/frontend/* "$DEPLOYPATH"
    - python3 scripts/configure_frontend.py --target "$DEPLOYPATH/index.html"
