---
deployment:
  tasks:
    - export DEPLOYPATH=$HOME/public_html/wp-content/uploads/greektax
    - /bin/mkdir -p "$DEPLOYPATH"
    - /bin/rsync -av --delete src/frontend/ "$DEPLOYPATH"/
    - if ! /bin/grep -q 'data-api-base' "$DEPLOYPATH/index.html"; then
        /bin/sed -i '0,/<head>/s//<head>\n    <meta data-api-base="https:\/\/cntanos.pythonanywhere.com\/api\/v1">/' "$DEPLOYPATH/index.html";
      fi
