#!/usr/bin/env python3
"""Bundle the configuration API responses into a static frontend module.

The frontend used to fetch year metadata, the application version, and the
per-year investment categories and deduction hints from the backend. This
script asks the Flask app for exactly those responses (one per year and
locale) and writes them to a generated ES module, so the browser can read them
without a network round trip and the data stays identical to the API.

Usage::

    python scripts/build_client_config.py          # rewrite the module
    python scripts/build_client_config.py --check  # fail if it is stale
"""

from __future__ import annotations

import argparse
import json
import sys
import warnings
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from greektax.backend.app import create_app  # noqa: E402

OUTPUT_PATH = (
    ROOT / "src" / "frontend" / "assets" / "scripts" / "data" / "client-config.generated.js"
)
TRANSLATIONS_DIR = SRC / "greektax" / "translations"

HEADER = (
    "// This file is auto-generated by scripts/build_client_config.py. Do not edit.\n"
    "// It holds the configuration API responses the frontend used to fetch.\n"
)


def _get_json(client: Any, url: str) -> Any:
    response = client.get(url)
    if response.status_code != 200:
        raise SystemExit(f"{url} returned HTTP {response.status_code}")
    return response.get_json()


def build_client_config() -> dict[str, Any]:
    with warnings.catch_warnings():
        # The app warns that no CORS origins are configured; irrelevant here.
        warnings.simplefilter("ignore", UserWarning)
        app = create_app()
    app.config.update(TESTING=True)
    client = app.test_client()

    locales = sorted(path.stem for path in TRANSLATIONS_DIR.glob("*.json"))
    years_payload = _get_json(client, "/api/v1/config/years")
    years = [entry["year"] for entry in years_payload["years"]]

    investment: dict[str, dict[str, Any]] = {}
    deductions: dict[str, dict[str, Any]] = {}
    for year in years:
        investment[str(year)] = {}
        deductions[str(year)] = {}
        for locale in locales:
            investment[str(year)][locale] = _get_json(
                client, f"/api/v1/config/{year}/investment-categories?locale={locale}"
            )
            deductions[str(year)][locale] = _get_json(
                client, f"/api/v1/config/{year}/deductions?locale={locale}"
            )

    return {
        "meta": _get_json(client, "/api/v1/config/meta"),
        "years": years_payload,
        "locales": locales,
        "investment": investment,
        "deductions": deductions,
    }


def render_module(config: dict[str, Any]) -> str:
    # ensure_ascii keeps the module free of characters (such as U+2028) that
    # are valid JSON but awkward in JavaScript source.
    body = json.dumps(config, ensure_ascii=True, indent=1, sort_keys=True)
    return f"{HEADER}export const CLIENT_CONFIG = Object.freeze({body});\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if the committed module differs from the API output",
    )
    args = parser.parse_args(argv)

    content = render_module(build_client_config())

    if args.check:
        if not OUTPUT_PATH.exists() or OUTPUT_PATH.read_text("utf-8") != content:
            print(
                f"{OUTPUT_PATH.relative_to(ROOT)} is stale. "
                "Run python scripts/build_client_config.py and commit the result."
            )
            return 1
        print(f"{OUTPUT_PATH.relative_to(ROOT)} is current.")
        return 0

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(content, "utf-8")
    print(f"Wrote {OUTPUT_PATH.relative_to(ROOT)}.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
