#!/usr/bin/env python3
"""Bundle configuration and engine data into static frontend modules.

``client-config.generated.js`` holds the configuration API responses the
frontend used to fetch (year metadata, the application version, and the
per-year investment categories and deduction hints, per locale). The script
asks the Flask app for exactly those responses, so the data stays identical
to the API.

``engine-data.generated.js`` holds what the client-side calculation engine
needs: each year's parsed and validated configuration (as loaded by
``year_config.py``) and the backend translation catalogues used for result
labels.

Usage::

    python scripts/build_client_config.py          # rewrite the module
    python scripts/build_client_config.py --check  # fail if it is stale
"""

from __future__ import annotations

import argparse
import json
import sys
import warnings
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from greektax.backend.app import create_app  # noqa: E402
from greektax.backend.app.localization.catalog import (  # noqa: E402
    get_translator,
)
from greektax.backend.config.year_config import (  # noqa: E402
    MultiRateBracket,
    ProgressiveTaxBracket,
    YearConfiguration,
    available_years,
    load_year_configuration,
)

DATA_DIR = ROOT / "src" / "frontend" / "assets" / "scripts" / "data"
OUTPUT_PATH = DATA_DIR / "client-config.generated.js"
ENGINE_OUTPUT_PATH = DATA_DIR / "engine-data.generated.js"
TRANSLATIONS_DIR = SRC / "greektax" / "translations"

HEADER = (
    "// This file is auto-generated by scripts/build_client_config.py. Do not edit.\n"
    "// It holds the configuration API responses the frontend used to fetch.\n"
)
ENGINE_HEADER = (
    "// This file is auto-generated by scripts/build_client_config.py. Do not edit.\n"
    "// It holds the year configuration and labels used by the calculation engine.\n"
)


def _get_json(client: Any, url: str) -> Any:
    response = client.get(url)
    if response.status_code != 200:
        raise SystemExit(f"{url} returned HTTP {response.status_code}")
    return response.get_json()


def build_client_config() -> dict[str, Any]:
    with warnings.catch_warnings():
        # The app warns that no CORS origins are configured; irrelevant here.
        warnings.simplefilter("ignore", UserWarning)
        app = create_app()
    app.config.update(TESTING=True)
    client = app.test_client()

    locales = sorted(path.stem for path in TRANSLATIONS_DIR.glob("*.json"))
    years_payload = _get_json(client, "/api/v1/config/years")
    years = [entry["year"] for entry in years_payload["years"]]

    investment: dict[str, dict[str, Any]] = {}
    deductions: dict[str, dict[str, Any]] = {}
    for year in years:
        investment[str(year)] = {}
        deductions[str(year)] = {}
        for locale in locales:
            investment[str(year)][locale] = _get_json(
                client, f"/api/v1/config/{year}/investment-categories?locale={locale}"
            )
            deductions[str(year)][locale] = _get_json(
                client, f"/api/v1/config/{year}/deductions?locale={locale}"
            )

    return {
        "meta": _get_json(client, "/api/v1/config/meta"),
        "years": years_payload,
        "locales": locales,
        "investment": investment,
        "deductions": deductions,
    }


def _rate_table(rates: dict[int, float]) -> list[list[float]]:
    return [[count, rate] for count, rate in sorted(rates.items())]


def _engine_brackets(brackets: Any) -> list[dict[str, Any]]:
    serialised: list[dict[str, Any]] = []
    bracket: ProgressiveTaxBracket
    for bracket in brackets:
        if isinstance(bracket, MultiRateBracket):
            serialised.append(
                {
                    "upper": bracket.upper_bound,
                    "household": _rate_table(bracket.household.dependants),
                    "youth": {
                        band: {
                            "dependants": _rate_table(table.dependants),
                            "rate": table.rate,
                        }
                        for band, table in sorted(bracket.youth_rates.items())
                    },
                }
            )
        else:
            serialised.append({"upper": bracket.upper_bound, "rate": bracket.rate})
    return serialised


def _engine_year(config: YearConfiguration) -> dict[str, Any]:
    employment = config.employment
    pension = config.pension
    trade_fee = config.freelance.trade_fee
    rules = config.rules
    deduction_rules = config.deductions.rules

    def payroll(section: Any) -> dict[str, Any]:
        return {
            "allowed": list(section.payroll.allowed_payments_per_year),
            "default": section.payroll.default_payments_per_year,
        }

    def tax_credit(section: Any) -> dict[str, Any]:
        credit = section.tax_credit
        return {
            "amounts_by_children": _rate_table(credit.amounts_by_children),
            "incremental_amount_per_child": credit.incremental_amount_per_child,
            "income_reduction_exempt_from_dependants": (
                credit.income_reduction_exempt_from_dependants
            ),
        }

    return {
        "year": config.year,
        "rules": {
            "age_reference_year": rules.age_reference_year,
            "youth_bands": [list(band) for band in rules.youth_bands],
            "youth_relief_categories": list(rules.youth_relief_categories),
            "residency_transfer_taxable_share": rules.residency_transfer_taxable_share,
            "max_birth_year_with_income": rules.max_birth_year_with_income,
            "salary_credit": {
                "income_categories": list(rules.salary_credit.income_categories),
                "reduction_threshold": rules.salary_credit.reduction_threshold,
                "reduction_step": rules.salary_credit.reduction_step,
                "reduction_per_step": rules.salary_credit.reduction_per_step,
                "shared_across_general_income": (
                    rules.salary_credit.shared_across_general_income
                ),
            },
        },
        "employment": {
            "brackets": _engine_brackets(employment.brackets),
            "payroll": payroll(employment),
            "contributions": {
                "employee_rate": employment.contributions.employee_rate,
                "employer_rate": employment.contributions.employer_rate,
                "monthly_salary_cap": employment.contributions.monthly_salary_cap,
            },
            "tax_credit": tax_credit(employment),
        },
        "pension": {"payroll": payroll(pension), "tax_credit": tax_credit(pension)},
        "freelance": {
            "efka_categories": [
                {"id": category.id, "monthly_amount": category.monthly_amount}
                for category in config.freelance.efka_categories
            ],
            "trade_fee": {
                "standard_amount": trade_fee.standard_amount,
                "reduced_amount": trade_fee.reduced_amount,
                "newly_self_employed_reduction_years": (
                    trade_fee.newly_self_employed_reduction_years
                ),
                "fee_sunset": trade_fee.fee_sunset,
                "sunset": (
                    {"status_key": trade_fee.sunset.status_key, "year": trade_fee.sunset.year}
                    if trade_fee.sunset
                    else None
                ),
            },
        },
        "rental": {"brackets": _engine_brackets(config.rental.brackets)},
        # A list keeps the YAML order, which decides the order of investment items.
        "investment": {"rates": [[key, rate] for key, rate in config.investment.rates.items()]},
        "deductions": {
            "donations": {
                "credit_rate": deduction_rules.donations.credit_rate,
                "income_cap_rate": deduction_rules.donations.income_cap_rate,
            },
            "medical": {
                "credit_rate": deduction_rules.medical.credit_rate,
                "income_threshold_rate": deduction_rules.medical.income_threshold_rate,
                "max_credit": deduction_rules.medical.max_credit,
            },
            "education": {
                "credit_rate": deduction_rules.education.credit_rate,
                "max_eligible_expense": deduction_rules.education.max_eligible_expense,
            },
            "insurance": {
                "credit_rate": deduction_rules.insurance.credit_rate,
                "max_eligible_expense": deduction_rules.insurance.max_eligible_expense,
            },
        },
    }


def build_engine_data() -> dict[str, Any]:
    locales = sorted(path.stem for path in TRANSLATIONS_DIR.glob("*.json"))
    return {
        "years": {
            str(year): _engine_year(load_year_configuration(year))
            for year in available_years()
        },
        "locales": locales,
        "translations": {
            locale: dict(get_translator(locale)._messages) for locale in locales
        },
    }


def _render(header: str, name: str, data: dict[str, Any]) -> str:
    # ensure_ascii keeps the module free of characters (such as U+2028) that
    # are valid JSON but awkward in JavaScript source.
    body = json.dumps(data, ensure_ascii=True, indent=1, sort_keys=True)
    return f"{header}export const {name} = Object.freeze({body});\n"


def render_module(config: dict[str, Any]) -> str:
    return _render(HEADER, "CLIENT_CONFIG", config)


def render_engine_module(data: dict[str, Any]) -> str:
    return _render(ENGINE_HEADER, "ENGINE_DATA", data)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if the committed module differs from the API output",
    )
    args = parser.parse_args(argv)

    outputs = {
        OUTPUT_PATH: render_module(build_client_config()),
        ENGINE_OUTPUT_PATH: render_engine_module(build_engine_data()),
    }

    if args.check:
        stale = [
            path
            for path, content in outputs.items()
            if not path.exists() or path.read_text("utf-8") != content
        ]
        for path in stale:
            print(
                f"{path.relative_to(ROOT)} is stale. "
                "Run python scripts/build_client_config.py and commit the result."
            )
        if stale:
            return 1
        print("Bundled frontend data is current.")
        return 0

    DATA_DIR.mkdir(parents=True, exist_ok=True)
    for path, content in outputs.items():
        path.write_text(content, "utf-8")
        print(f"Wrote {path.relative_to(ROOT)}.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
